/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradieRouteImport } from './routes/tradie'
import { Route as ResumeBuilderRouteImport } from './routes/resume-builder'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as ItHelpDeskRouteImport } from './routes/it-help-desk'
import { Route as GradeCalculatorRouteImport } from './routes/grade-calculator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as BlogTagsIndexRouteImport } from './routes/blog/tags/index'
import { Route as AuthenticatedEditorIndexRouteImport } from './routes/_authenticated/editor/index'
import { Route as BlogTagsTagRouteImport } from './routes/blog/tags/$tag'
import { Route as AuthenticatedEditorSlugRouteImport } from './routes/_authenticated/editor/$slug'

const TradieRoute = TradieRouteImport.update({
  id: '/tradie',
  path: '/tradie',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ItHelpDeskRoute = ItHelpDeskRouteImport.update({
  id: '/it-help-desk',
  path: '/it-help-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GradeCalculatorRoute = GradeCalculatorRouteImport.update({
  id: '/grade-calculator',
  path: '/grade-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagsIndexRoute = BlogTagsIndexRouteImport.update({
  id: '/blog/tags/',
  path: '/blog/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditorIndexRoute =
  AuthenticatedEditorIndexRouteImport.update({
    id: '/editor/',
    path: '/editor/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const BlogTagsTagRoute = BlogTagsTagRouteImport.update({
  id: '/blog/tags/$tag',
  path: '/blog/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditorSlugRoute = AuthenticatedEditorSlugRouteImport.update({
  id: '/editor/$slug',
  path: '/editor/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/grade-calculator': typeof GradeCalculatorRoute
  '/it-help-desk': typeof ItHelpDeskRoute
  '/navigation': typeof NavigationRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/tradie': typeof TradieRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/editor/$slug': typeof AuthenticatedEditorSlugRoute
  '/blog/tags/$tag': typeof BlogTagsTagRoute
  '/editor': typeof AuthenticatedEditorIndexRoute
  '/blog/tags': typeof BlogTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/grade-calculator': typeof GradeCalculatorRoute
  '/it-help-desk': typeof ItHelpDeskRoute
  '/navigation': typeof NavigationRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/tradie': typeof TradieRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/editor/$slug': typeof AuthenticatedEditorSlugRoute
  '/blog/tags/$tag': typeof BlogTagsTagRoute
  '/editor': typeof AuthenticatedEditorIndexRoute
  '/blog/tags': typeof BlogTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/grade-calculator': typeof GradeCalculatorRoute
  '/it-help-desk': typeof ItHelpDeskRoute
  '/navigation': typeof NavigationRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/tradie': typeof TradieRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/_authenticated/editor/$slug': typeof AuthenticatedEditorSlugRoute
  '/blog/tags/$tag': typeof BlogTagsTagRoute
  '/_authenticated/editor/': typeof AuthenticatedEditorIndexRoute
  '/blog/tags/': typeof BlogTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/grade-calculator'
    | '/it-help-desk'
    | '/navigation'
    | '/resume-builder'
    | '/tradie'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog'
    | '/projects'
    | '/editor/$slug'
    | '/blog/tags/$tag'
    | '/editor'
    | '/blog/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/grade-calculator'
    | '/it-help-desk'
    | '/navigation'
    | '/resume-builder'
    | '/tradie'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog'
    | '/projects'
    | '/editor/$slug'
    | '/blog/tags/$tag'
    | '/editor'
    | '/blog/tags'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/grade-calculator'
    | '/it-help-desk'
    | '/navigation'
    | '/resume-builder'
    | '/tradie'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog/'
    | '/projects/'
    | '/_authenticated/editor/$slug'
    | '/blog/tags/$tag'
    | '/_authenticated/editor/'
    | '/blog/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GradeCalculatorRoute: typeof GradeCalculatorRoute
  ItHelpDeskRoute: typeof ItHelpDeskRoute
  NavigationRoute: typeof NavigationRoute
  ResumeBuilderRoute: typeof ResumeBuilderRoute
  TradieRoute: typeof TradieRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  BlogTagsTagRoute: typeof BlogTagsTagRoute
  BlogTagsIndexRoute: typeof BlogTagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tradie': {
      id: '/tradie'
      path: '/tradie'
      fullPath: '/tradie'
      preLoaderRoute: typeof TradieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-builder': {
      id: '/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-help-desk': {
      id: '/it-help-desk'
      path: '/it-help-desk'
      fullPath: '/it-help-desk'
      preLoaderRoute: typeof ItHelpDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-calculator': {
      id: '/grade-calculator'
      path: '/grade-calculator'
      fullPath: '/grade-calculator'
      preLoaderRoute: typeof GradeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tags/': {
      id: '/blog/tags/'
      path: '/blog/tags'
      fullPath: '/blog/tags'
      preLoaderRoute: typeof BlogTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/editor/': {
      id: '/_authenticated/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AuthenticatedEditorIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/blog/tags/$tag': {
      id: '/blog/tags/$tag'
      path: '/blog/tags/$tag'
      fullPath: '/blog/tags/$tag'
      preLoaderRoute: typeof BlogTagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/editor/$slug': {
      id: '/_authenticated/editor/$slug'
      path: '/editor/$slug'
      fullPath: '/editor/$slug'
      preLoaderRoute: typeof AuthenticatedEditorSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedEditorSlugRoute: typeof AuthenticatedEditorSlugRoute
  AuthenticatedEditorIndexRoute: typeof AuthenticatedEditorIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedEditorSlugRoute: AuthenticatedEditorSlugRoute,
  AuthenticatedEditorIndexRoute: AuthenticatedEditorIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GradeCalculatorRoute: GradeCalculatorRoute,
  ItHelpDeskRoute: ItHelpDeskRoute,
  NavigationRoute: NavigationRoute,
  ResumeBuilderRoute: ResumeBuilderRoute,
  TradieRoute: TradieRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  BlogTagsTagRoute: BlogTagsTagRoute,
  BlogTagsIndexRoute: BlogTagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
